name: "New Snippet"
description: "Capture a quote/idea for the Tackboard (Inbox -> Garden)."
title: "Snippet: "
labels: ["snippet", "inbox"]
body:
  - type: markdown
    attributes:
      value: |
        Capture quickly. Later you can promote to Garden by changing status to `garden` in the Markdown snippet file.

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - inbox
        - garden
    validations:
      required: true

  - type: dropdown
    id: source_type
    attributes:
      label: Source type
      options:
        - podcast
        - book
        - article
        - paper
        - video
        - talk
        - other
    validations:
      required: true

  - type: input
    id: source_title
    attributes:
      label: Source title
      placeholder: "Episode / book / article title"
    validations:
      required: true

  - type: input
    id: source_creator
    attributes:
      label: Creator
      placeholder: "Host / author / speaker"
    validations:
      required: false

  - type: input
    id: source_url
    attributes:
      label: Source URL
      placeholder: "https://..."
    validations:
      required: false

  - type: input
    id: source_locator
    attributes:
      label: Locator
      placeholder: "timestamp (43:10), page, chapter, section, etc."
    validations:
      required: false

  - type: textarea
    id: highlight
    attributes:
      label: Highlight (quote or distilled idea)
      placeholder: "1–3 lines ideal"
    validations:
      required: true

  - type: textarea
    id: takeaway
    attributes:
      label: Why it struck me (takeaway)
      placeholder: "1–2 sentences"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: "decision-making, epistemics, embodiment"
    validations:
      required: false

  - type: input
    id: topics
    attributes:
      label: Topics (comma-separated, higher-level buckets)
      placeholder: "thinking-tools, ai-literacy"
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact (optional)
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: "Extra context, how you might use it, related links..."
    validations:
      required: false

